### ISSUE TITLE
[ Enhancement ] fix typo?

### ISSUE THREAD

**Issue by ComputerHavoc** [LonelessCodes/Soundbort#2]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [ x] Double checked existing Issues/Pull Requests for a similar suggestion.

**Describe the change you would like to see**
/getting-started command shows you an info page and the contributing link brings you to https://github.com/LonelessCodes/trixiebot
maybe change it to 
https://github.com/LonelessCodes/Soundbort

**Why should we change it that way?**
this isn't trixiebot

**Comment by LonelessCodes** [comment]
Thank you. That's embarrassing. Fixed in 23192fec818b7eabb68c5dcccba274bb9f5b7596
