### ISSUE TITLE
remove RickRoll

### ISSUE THREAD

**Issue by ComputerHavoc** [LonelessCodes/Soundbort#4]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X ] Double checked existing Issues/Pull Requests for a similar suggestion.

**Describe the change you would like to see**
remove rickroll sound from standard library 

**Why should we change it that way?**
rickroll song is copyrighted and could cause potential copyright problems and shouldn't be in the default sounds

**Comment by LonelessCodes** [comment]
It is a clip shorter than 15 seconds. I am covered by the new copyright law of the EU.
