### ISSUE TITLE
[ Bug ] Disk space Error

### ISSUE THREAD

**Issue by Bribruh123** [LonelessCodes/Soundbort#59]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X ] Made sure this is actual unintended behaviour.
- [X ] Double checked the /command descriptions (if this is command related) for potential misunderstandings.

**Describe the bug**
Recieve "Disk space is running out. Please inform the developer." when attempting to upload a new sound. 

**To Reproduce**
Upload Sounds

**Expected behavior**
Upon upload command, sound should be uploaded to soundboard in server.

**Additional context**
![image](https://github.com/Soundbort/Soundbort/assets/87781032/a9712e58-8bb2-4be1-b47a-9fc376d1dd2e)

**Comment by LonelessCodes** [comment]
Sorry about the delay. It has been fixed

**Comment by groovenet** [comment]
I've got exactly the same problem. Doesn't seem to be fixed for me.
Or do I need to install Soundbort again or something?
![grafik](https://github.com/Soundbort/Soundbort/assets/170766686/40acee80-2268-48be-a60e-4f501141b2fd)
